[workspace]
members = ["macros"]

[package]
name = "evergreen_relations"
version = "0.1.0"
edition = "2021"

[dependencies]
evergreen_relations_macros = { path = "macros" }
bevy_ecs = { version = "0.15", default-features = false }
smallvec = { version = "1.13", features = ["const_generics"] }
